version: '3.8'
  
services:
  frontend:
    image: nguyengianguit/frontend-image:latest
    ports:
      - "3000:3000"
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]  # Thêm dòng này

  authentication_services:
    image: nguyengianguit/auth-service-image:latest
    ports:
      - "3003:3003"
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]  # Thêm dòng này


  employee_services:
    image: nguyengianguit/employee-services-image:latest
    ports:
      - "3001:3001"
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]  # Thêm dòng này


  department_services:
    image: nguyengianguit/department_services_image:latest
    ports:
      - "3002:3002"
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]  # Thêm dòng này


  db:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  app_network:
    driver: overlay

volumes:
  mongo-data:
