name: CI/CD for Microservices on Docker Swarm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Clone mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build và push từng Docker image
      - name: Build and Push Images
        run: |
          docker build -t nguyengianguit/frontend-image:latest ./Front-end
          docker push nguyengianguit/frontend-image:latest

          docker build -t nguyengianguit/employee-services-image:latest ./employee_services
          docker push nguyengianguit/employee-services-image:latest

          docker build -t nguyengianguit/auth-service-image:latest ./Authentication_services
          docker push nguyengianguit/auth-service-image:latest

          docker build -t nguyengianguit/department_services_image:latest ./department_services
          docker push nguyengianguit/department_services_image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      # Bước 1: Triển khai Docker Swarm qua SSH
      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          debug: true
          script: |
            docker stack deploy --compose-file Docker-compose.yml my_swarm_stack
