name: CI/CD for Microservices on Docker Swarm

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          docker build -t nguyengianguit/frontend-image:latest ./Front-end
          docker push nguyengianguit/frontend-image:latest
          docker build -t nguyengianguit/employee-services-image:latest ./employee_services
          docker push nguyengianguit/employee-services-image:latest
          docker build -t nguyengianguit/auth-service-image:latest ./Authentication_services
          docker push nguyengianguit/auth-service-image:latest
          docker build -t nguyengianguit/department_services_image:latest ./department_services
          docker push nguyengianguit/department_services_image:latest

  deploy:
    needs: build_and_push # Chỉ chạy sau khi build_and_push hoàn thành
    runs-on: self-hosted

    steps:
      - name: Deploy to Docker Swarm
        run: |
          cd ~/webapp/WebQLNhanVien
          docker stack deploy --compose-file Docker-compose.yml my_swarm_stack
